[project]
name = "ppt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=5.4.0",
    "mcp>=1.9.4",
    "python-pptx>=1.0.2",
]
